### ISSUE TITLE
Tiempo para volver a hacer esto?

### ISSUE THREAD

**Issue by aallfredo** [programadorespuertorico/puerto-rico-salary#4]
Algun cambio que queramos en la metodologia. @jamesxv7 @jlugaro

**Comment by jamesxv7** [comment]
La idea es lograr algo parecido a lo que hace Robert Half Technology pero enfocado exclusivamente a PR y mercado latinoamericano. 

https://www.roberthalf.com/technology/salary-center-for-technology-professionals

**Comment by aallfredo** [comment]
kay dejame darle cabeza a eso y reformulo el form.  te aviso antes del domingo.

**Comment by jamesxv7** [comment]
No tenemos que ajorarlo podemos darle casco con calma. Hay que trabajar en el alcance. Cómo hacer para que la gente se motive a contestar y compartir la encuesta.

**Comment by jamesxv7** [comment]
Creo que el trabajo realizado para la encuesta durante el 2016/17 fue satisfactorio.
